services:
  kalilinux:
    hostname: kali
    build:
      context: ./
      dockerfile: Dockerfile
    image: 'kalilinux-docker-vnc-custom:lastest'
    cap_add:
      - NET_ADMIN
    ports:
      - ${BIND:-0.0.0.0:8080}:8080
      - "8088:8088" # for vs-code remote
    environment:
      SHELL: /bin/zsh
      PASSWORD: ${PASSWORD:-kali}
      TZ: Asia/Taipei
      # DOTFILES_FORCE: 1   # force reinstall dotfiles
      # DOTFILES_DISABLE: 1 # skip dotfiles installation
      # BOOTSTRAP_STRICT: 0 # if bootstrap failed, still continue to start container
    volumes:
      # Persistant kali home directory
      - kali-home:/home/kali
    # entrypoint: ["/bin/bash", "/startup.sh"] // override entrypoint

volumes:
  kali-home: {}
